# -*- coding: utf-8 -*-
"""thaicons.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-edX-vqxXqY5POFp-4XMJuaosIHU5pL4
"""

import tkinter as tk
from tkinter import font

# Thai consonants and their names
thai_consonants = {
    "ก": "gor kai",
    "ข": "khor khai",
    "ฃ": "khor khuat",
    "ค": "khor khwai",
    "ฅ": "khor khon",
    "ฆ": "khor ra-khang",
    "ง": "ngor ngoo"
}

# Convert to list for easy indexing
consonants = list(thai_consonants.keys())
names = list(thai_consonants.values())

# Game state
current_index = 0
is_flipped = False

def flip_card():
    global is_flipped
    if is_flipped:
        # Show the consonant
        flashcard.config(text=consonants[current_index], font=("Arial", 100))
        is_flipped = False
    else:
        # Show the name
        flashcard.config(text=names[current_index], font=("Arial", 40))
        is_flipped = True

def next_card():
    global current_index, is_flipped
    current_index += 1
    if current_index >= len(consonants):
        current_index = 0  # Restart from the beginning
    is_flipped = False
    flashcard.config(text=consonants[current_index], font=("Arial", 100))

# Set up the GUI
root = tk.Tk()
root.title("Thai Consonant Flashcards")

# Set window size
root.geometry("400x300")

# Flashcard Label
flashcard = tk.Label(root, text=consonants[current_index], font=("Arial", 100), pady=50)
flashcard.pack()

# Flip Button
flip_button = tk.Button(root, text="Flip", command=flip_card, bg="blue", fg="white", padx=20, pady=10)
flip_button.pack(side="left", padx=10)

# Next Button
next_button = tk.Button(root, text="Next", command=next_card, bg="green", fg="white", padx=20, pady=10)
next_button.pack(side="right", padx=10)

# Start the GUI loop
root.mainloop()